name: Test Release

on: pull_request

jobs:
  tests:
    name: Test or Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        env:
          CI: true
        run: |
          yarn install
          yarn ci
      - name: Build All Packages
        run: yarn run build

  test_publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - env:
          CI: true
        run: |
          yarn install
          yarn ci
      - env:
          CI: true
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > /home/runner/work/_temp/.npmrc
          npx semantic-release --dry-run --debug -b $GITHUB_HEAD_REF
